config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources  :books
  root 'books#index'
end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :books
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :books
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :find_book, only: [:show, :edit, :update, :destroy]



	def index

		if params[:category].blank?
			@books = Book.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@books = Book.where(:category_id => @category_id).order("created_at DESC")
		end
	end

	def new
		@book = current_user.books.build
		@categories = Category.all.map { |c| [c.name, c.id]  }
	end

	def create
		@book = current_user.books.build(book_params)
		@book.category_id = params[:category_id]
		if @book.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def show
		
	end	
	def edit
		@categories = Category.all.map { |c| [c.name, c.id]  }
	end
	def update
		@categories = Category.all.map { |c| [c.name, c.id]  }
		if @book.update(book_params)
			redirect_to book_path(@book)
		else
			render 'edit'
		end
		
	end

	def destroy
		@book.destroy
		redirect_to root_path
	end


	private
		def book_params
			params.require(:book).permit(:title, :description, :author, :category_id)
		end

		def find_book
			@book = Book.find(params[:id])
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book, :html => { :multipart => true} do  |f| %>

  <%= select_tag( :category_id, options_for_select(@categories), :promt => "Seleccione Cateforia", :class=>"form-control") %>
  <%= f.input :title, label: " Titulo del Libro" %>
  <%= f.input :description %>
  <%= f.input :author %>
  <%= f.button :submit %>
<% end %>

app/views/books/edit.html.erb
<h2>Edit Book</h2>
<%= simple_form_for @book, :html => { :multipart => true} do  |f| %>

  <%= f.select :category_id,  @categories, { include_blank: false },  { :class => "form-control"} %>

  <%= f.input :title, label: " Titulo del Libro" %>
  <%= f.input :description %>
  <%= f.input :author %>
  <%= f.button :submit %>
<% end %>

app/views/books/index.html.erb
<h1>Libros de  <%= params[:category] %></h1>

<% @books.each do |book| %>
	<h2> <%= link_to book.title, book_path(book) %></h2>
<% end%>

app/views/books/new.html.erb
<h1>New Book</h1>

<%=  render 'form' %>

app/views/books/show.html.erb
 <h2><strong> <%= @book.title %></strong></h2>
 <h3> <%= @book.author %></h3>
 <h3> <%= @book.category.name %></h3>
 <p> <%= @book.description %></p>

<%= link_to "Atraz ", root_path  %>

<% if user_signed_in?  %>
	<% if current_user.id == @book.user_id  %>

		<%= link_to "Editar ", edit_book_path(@book)  %>
		<%= link_to "Borrar  ", book_path(@book), method: :delete, data: { confirm: "Esta seguro de Eliminar?"}  %>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mybook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to  "My Book", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Crear Usuario", new_user_registration_path %></li>
        <% if user_signed_in?  %>
       		<li> <%= link_to "Salir", destroy_user_session_path, method: :delete    %></li>
       		
        <% else%>
        	<li> <%= link_to "Ingresar", new_user_session_path    %></li>
        <% end%>
      </ul>


      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in?  %>
       		<li> <%= link_to "Agregar Libro", new_book_path %></li>
        <% end%>   
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categorias <span class="caret"></span></a>
          <ul class="dropdown-menu">

            <% Category.all.each do |category| %>
				<li class="<%= 'active' if params[:category] == category.name %>">
					<%= link_to category.name, books_path(category: category.name), class: "link" %>
				</li>
			<% end %>
            
          </ul>
        </li>
      </ul>



    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
	
	 <p class="notice"><%= notice %></p>
	 <p class="alert"><%= alert %></p>

	<%= yield %>

</div>


</body>
</html>